# Generated by Django 3.0.5 on 2021-03-28 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210327_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['username']},
        ),
    ]
