# Generated by Django 3.0.5 on 2021-03-28 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210328_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['username']},
        ),
    ]
