# Generated by Django 3.0.5 on 2021-03-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210328_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(
                choices=[
                    ('US',
                     'User'),
                    ('MD',
                     'Moderator'),
                    ('AD',
                     'Admin')],
                default='US',
                max_length=10),
        ),
    ]
