# Generated by Django 3.0.5 on 2021-03-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210330_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_code',
            field=models.SlugField(null=True),
        ),
    ]
