# Generated by Django 3.0.5 on 2021-03-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210330_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(
                choices=[
                    ('US',
                     'user'),
                    ('MD',
                     'moderator'),
                    ('AD',
                     'admin')],
                default='US',
                max_length=10),
        ),
    ]
