# Generated by Django 3.0.5 on 2021-03-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210330_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(
                choices=[
                    ('user',
                     'User'),
                    ('moderator',
                     'Moderator'),
                    ('admin',
                     'Admin')],
                default='user',
                max_length=10),
        ),
    ]
