# Generated by Django 3.0.5 on 2021-03-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210331_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={
                'ordering': ['username'],
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(
                blank=True,
                max_length=500,
                verbose_name='Информация о пользователе'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(
                max_length=50,
                unique=True,
                verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(
                choices=[
                    ('user',
                     'User'),
                    ('moderator',
                     'Moderator'),
                    ('admin',
                     'Admin')],
                default='user',
                max_length=10,
                verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_code',
            field=models.SlugField(
                null=True, verbose_name='Код подтверждения'),
        ),
    ]
